```
version: '3.8'

services:
  web:
    build: . # Build the image using the Dockerfile in the current directory
    container_name: fastapi_app_web
    # Command to run the FastAPI application using Uvicorn
    # Assumes your main FastAPI app is in 'main.py' and the FastAPI instance is named ''app''
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app # Mount the current directory into the container for live code changes (dev only)
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - .env # Load environment variables from a .env file (e.g., for secrets)
    depends_on:
      - db # Ensure the database service starts before the web service
    networks:
      - app_network # Connect to a custom network

  # PostgreSQL Database Service
  db:
    image: postgres:16-alpine # Use a lightweight PostgreSQL image
    container_name: fastapi_app_db
    volumes:
      - pg_data:/var/lib/postgresql/data # Persistent volume for database data
    environment:
      POSTGRES_DB: ${DB_NAME} # Database name from .env
      POSTGRES_USER: ${DB_USER} # Database user from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Database password from .env
    ports:
      - "5432:5432" # Optional: Expose database port to host (useful for connecting with external tools)
    networks:
      - app_network # Connect to a custom network
```